In [1]:
from mnist import MNIST
mndata = MNIST('./data')
images, labels = mndata.load_training()
test_images, test_labels = mndata.load_testing()

In [27]:
import numpy as np

images = np.array(images)

test_images = np.array(test_images)
test_labels = np.array(test_labels)

(60000L, 784L)
(10000L, 784L)


In [19]:
# problem 1 

from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=1)

neigh.fit(images[:30000], labels[:30000]) 

predictions = neigh.predict(test_images[:2000])


In [33]:
# problem 1 
from sklearn.metrics import confusion_matrix

correct = sum([a == b for a,b in zip(test_labels[:2000], predictions)])

print "success rate =",correct/2000.0 * 100,"%"
print "\ncounfustion matrix = \n",confusion_matrix(test_labels[:2000], predictions)


success rate = 94.25 %

counfustion matrix = 
[[173   0   0   0   0   0   1   1   0   0]
 [  0 232   1   0   0   1   0   0   0   0]
 [  3   2 206   2   0   0   2   4   0   0]
 [  0   1   1 193   0   3   1   3   3   2]
 [  0   2   0   0 204   0   2   0   0   9]
 [  0   0   0   8   1 167   1   1   0   1]
 [  1   0   0   0   1   2 173   0   1   0]
 [  0   6   1   1   2   0   0 192   0   3]
 [  3   0   2   8   3   6   0   2 164   4]
 [  1   1   0   3   3   1   0   2   2 181]]


In [34]:
# problem 2 
from sklearn import linear_model
clf = linear_model.SGDClassifier()
clf.fit(images[:30000], labels[:30000])

predictions = clf.predict(test_images[:2000])

In [35]:
# problem 2
from sklearn.metrics import confusion_matrix

correct = sum([a == b for a,b in zip(test_labels[:2000], predictions)])

print "success rate =",correct/2000.0 * 100,"%"
print "\ncounfustion matrix = \n",confusion_matrix(test_labels[:2000], predictions)


success rate = 82.95 %

counfustion matrix = 
[[130   0  16   2   0  11   8   0   8   0]
 [  0 225   4   0   0   0   1   0   4   0]
 [  0   1 203   2   1   0   3   3   5   1]
 [  0   0   7 191   1   3   0   2   2   1]
 [  0   0  11   2 187   0   4   2   5   6]
 [  0   0   4  12   1 149   1   2  10   0]
 [  3   1  12   2   0   4 154   0   2   0]
 [  0   3  31  16   1   1   1 145   2   5]
 [  1   3  18  14   5  10   1   2 138   0]
 [  0   2   6  16  17   4   0   9   3 137]]
