In [2]:
from mnist import MNIST
mndata = MNIST('./mnist_data')
images, labels = mndata.load_training()
test_images, test_labels = mndata.load_testing()

In [3]:
import numpy as np

images = np.array(images)
labels = np.array(labels)

test_images = np.array(test_images)
test_labels = np.array(test_labels)

In [ ]:

images[:1]

In [ ]:
# problem 1 

from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=1)

neigh.fit(images[:30000], labels[:30000]) 

predictions = neigh.predict(test_images[:2000])


In [ ]:
# problem 1 
from sklearn.metrics import confusion_matrix

correct = sum([a == b for a,b in zip(test_labels[:2000], predictions)])

print "success rate =",correct/2000.0 * 100,"%"
print "\ncounfustion matrix = \n",confusion_matrix(test_labels[:2000], predictions)


In [ ]:
print 'test'

In [ ]:
# problem 2 
from sklearn import linear_model
clf = linear_model.SGDClassifier()
clf.fit(images[:30000], labels[:30000])

predictions = clf.predict(test_images[:2000])

In [ ]:
# problem 2
from sklearn.metrics import confusion_matrix

correct = sum([a == b for a,b in zip(test_labels[:2000], predictions)])

print "success rate =",correct/2000.0 * 100,"%"
print "\ncounfustion matrix = \n",confusion_matrix(test_labels[:2000], predictions)


In [ ]:
from sklearn import svm
X = images[:3000]
y = labels[:3000]
clf = svm.SVC()
clf.fit(X, y)  

predictions = clf.predict(test_images[:2000])

In [ ]:
from sklearn import svm
X = images[:15000]
y = labels[:15000]
#clf = svm.SVC(decision_function_shape='ovr',kernel='linear')
clf = svm.SVC(decision_function_shape='ovr',kernel='poly',degree=3)
clf.fit(X, y)  

predictions = clf.predict(test_images[:2000])

In [ ]:
# problem 2
from sklearn.metrics import confusion_matrix

correct = sum([a == b for a,b in zip(test_labels[:2000], predictions)])

print "success rate =",correct/2000.0 * 100,"%"
print "\ncounfustion matrix = \n",confusion_matrix(test_labels[:2000], predictions)

In [13]:
asdf = np.random.rand(6,5)
print asdf
print asdf[:2]


[[ 0.27591706  0.37186328  0.17641462  0.50630868  0.13748032]
 [ 0.08594063  0.14957183  0.84348856  0.42371007  0.92454301]
 [ 0.36416208  0.94654872  0.16501001  0.22683669  0.8544953 ]
 [ 0.26895067  0.44706188  0.47973966  0.68393591  0.46638173]
 [ 0.86552925  0.42106154  0.49438275  0.39650543  0.88694629]
 [ 0.24062939  0.59049156  0.40474142  0.17399624  0.57651526]]
[[ 0.27591706  0.37186328  0.17641462  0.50630868  0.13748032]
 [ 0.08594063  0.14957183  0.84348856  0.42371007  0.92454301]]


In [ ]:
import os
os.getcwd() 
sys.path.append(os.getcwd())


In [ ]:
__author__ = 'GongLi'
import os
os.getcwd() 
sys.path.append(os.getcwd())

from recognition import utils
from recognition import classification

def buildHistogram(path, level):

    # Read in vocabulary & data
    voc = utils.loadDataFromFile("Data/voc.pkl")
    trainData = utils.readImages("images/"+path)

    # Transform each feature into histogram
    featureHistogram = []
    labels = []

    index = 0
    for oneImage in trainData:

        featureHistogram.append(voc.buildHistogramForEachImageAtDifferentLevels(oneImage, level))
        labels.append(oneImage.label)

        index += 1

    utils.writeDataToFile("Data/"+path+"HistogramLevel" +str(level)+ ".pkl", featureHistogram)
    utils.writeDataToFile("Data/"+path+"labels.pkl", labels)



def main():

    # 1) build histograms

    # buildHistogram("testing", 0)
    # buildHistogram("training", 0)
    #
    # buildHistogram("testing", 1)
    # buildHistogram("training", 1)

    buildHistogram("testing", 2)
    buildHistogram("training", 2)

    # 2) classify
    print(" ")
    print("Level 2, 21 * (vocabulary size) dimensions, in this case, 6300 dimensions for each histogram")
    classification.SVM_Classify("Data/trainingHistogramLevel2.pkl", "Data/traininglabels.pkl", "Data/testingHistogramLevel2.pkl", "Data/testinglabels.pkl", "linear")
    classification.SVM_Classify("Data/trainingHistogramLevel2.pkl", "Data/traininglabels.pkl", "Data/testingHistogramLevel2.pkl", "Data/testinglabels.pkl", "poly")
    classification.SVM_Classify("Data/trainingHistogramLevel2.pkl", "Data/traininglabels.pkl", "Data/testingHistogramLevel2.pkl", "Data/testinglabels.pkl", "rbf")
    classification.SVM_Classify("Data/trainingHistogramLevel2.pkl", "Data/traininglabels.pkl", "Data/testingHistogramLevel2.pkl", "Data/testinglabels.pkl", "sigmoid")
    classification.SVM_Classify("Data/trainingHistogramLevel2.pkl", "Data/traininglabels.pkl", "Data/testingHistogramLevel2.pkl", "Data/testinglabels.pkl", "HI")

    classification.KNN_Classify("Data/trainingHistogramLevel2.pkl", "Data/traininglabels.pkl", "Data/testingHistogramLevel2.pkl", "Data/testinglabels.pkl")



main()


In [ ]:
import os
os.system('C:/Users/ljt/Documents/cogs260/project2/vlfeat-0.9.20/bin/win64/sift  tmp.pgm --output=temp.sift --read-frames=tmp.frame')

In [ ]:
#4


from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)



import tensorflow as tf
sess = tf.InteractiveSession()

In [ ]:
x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))

sess.run(tf.global_variables_initializer())

y = tf.matmul(x,W) + b

cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))

train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

for _ in range(1000):
  batch = mnist.train.next_batch(100)
  train_step.run(feed_dict={x: batch[0], y_: batch[1]})

In [ ]:
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))

accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

print(accuracy.eval(feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

In [ ]:
def weight_variable(shape):
  initial = tf.truncated_normal(shape, stddev=0.1)
  return tf.Variable(initial)

def bias_variable(shape):
  initial = tf.constant(0.1, shape=shape)
  return tf.Variable(initial)

def conv2d(x, W):
  return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
  return tf.nn.max_pool(x, ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1], padding='SAME')

In [ ]:
x_image = tf.reshape(x, [-1,28,28,1])


# first convolutional layer 
W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])

h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)

# second convolutional layer 
W_conv2 = weight_variable([5, 5, 32, 64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)

# densely/fully connected layer 
W_fc1 = weight_variable([7 * 7 * 64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

# dropout layer 
keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

# fully connected final layer 
W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

y_conv = tf.matmul(h_fc1_drop, W_fc2) + b_fc2

In [ ]:
cross_entropy = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y_conv))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
sess.run(tf.global_variables_initializer())
for i in range(1000):
  batch = mnist.train.next_batch(50)
  if i%100 == 0:
    train_accuracy = accuracy.eval(feed_dict={
        x:batch[0], y_: batch[1], keep_prob: 1.0})
    print("step %d, training accuracy %g"%(i, train_accuracy))
  train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})

print("test accuracy %g"%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))